# Generated by Django 5.2.13 on 2026-04-22 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the role', max_length=100, unique=True)),
                ('code', models.CharField(choices=[('admin', 'Administrator'), ('operator', 'Operator'), ('viewer', 'Viewer'), ('auditor', 'Auditor')], help_text='Code identifier for the role type', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the role')),
                ('permissions', models.JSONField(default=dict, help_text='JSON object containing permission codes and their granted status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'accounts_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='User email address (used for login)', max_length=255, unique=True)),
                ('username', models.CharField(blank=True, help_text='Optional username for display purposes', max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, help_text='User first name', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='User last name', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Whether this user can access the admin site')),
                ('is_system', models.BooleanField(default=False, help_text='Whether this is a system account (for node authentication)')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last time user logged in', null=True)),
                ('phone', models.CharField(blank=True, help_text='User phone number', max_length=20, null=True)),
                ('avatar', models.URLField(blank=True, help_text='URL to user avatar image', null=True)),
                ('preferences', models.JSONField(default=dict, help_text='User preferences and settings')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='hfl_user_set', related_query_name='hfl_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='hfl_user_set', related_query_name='hfl_user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='User role for RBAC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
                ('user', models.ForeignKey(help_text='User who owns this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'accounts_user_session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this token', max_length=100)),
                ('key', models.CharField(help_text='The actual token value (stored hashed in production)', max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='Prefix of the key for display purposes', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this token expires (null = never)', null=True)),
                ('scopes', models.JSONField(default=list, help_text='List of permission scopes for this token')),
                ('rate_limit', models.IntegerField(default=100, help_text='Maximum requests per minute allowed with this token')),
                ('user', models.ForeignKey(help_text='User who owns this token', on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'db_table': 'accounts_api_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='accounts_ap_key_07b1dd_idx'), models.Index(fields=['user', 'is_active'], name='accounts_ap_user_id_8e268c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_f3bc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='accounts_us_session_5ce38e_idx'),
        ),
    ]
