# Generated by Django 5.2.13 on 2026-04-29 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_tenant_to_models"),
    ]

    operations = [
        # Convert id from bigint to UUID using raw SQL (required for PostgreSQL)
        migrations.RunSQL(
            sql="""
            -- Drop primary key with CASCADE to automatically remove dependent foreign keys
            ALTER TABLE accounts_user DROP CONSTRAINT accounts_user_pkey CASCADE;
            -- Drop old id column
            ALTER TABLE accounts_user DROP COLUMN id;
            -- Add new UUID column as primary key
            ALTER TABLE accounts_user ADD COLUMN id uuid DEFAULT gen_random_uuid() PRIMARY KEY;
            -- Recreate foreign key constraints (Django will handle these via subsequent migrations/orm)
            """,
            reverse_sql="""
            -- This migration is not reversible for fresh databases
            SELECT 1;
            """,
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant_role",
            field=models.CharField(
                choices=[("admin", "Administrator"), ("member", "Member")],
                default="member",
                help_text="Role within the tenant",
                max_length=20,
            ),
        ),
    ]
