# Generated by Django 5.2.13 on 2026-04-29 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_tenant_to_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique identifier (UUID4 format)",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant_role",
            field=models.CharField(
                choices=[("admin", "Administrator"), ("member", "Member")],
                default="member",
                help_text="Role within the tenant",
                max_length=20,
            ),
        ),
    ]
