# Generated by Django 5.2.13 on 2026-04-29 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_tenant_to_models"),
    ]

    operations = [
        # Convert id from bigint to UUID using raw SQL (required for PostgreSQL)
        migrations.RunSQL(
            sql="""
            -- Drop existing primary key constraint
            ALTER TABLE accounts_user DROP CONSTRAINT accounts_user_pkey;
            -- Add new UUID column
            ALTER TABLE accounts_user ADD COLUMN id_new uuid DEFAULT gen_random_uuid();
            -- For empty table (fresh db), just set the UUID (if any rows existed)
            UPDATE accounts_user SET id_new = gen_random_uuid();
            -- Drop old id column
            ALTER TABLE accounts_user DROP COLUMN id;
            -- Rename new column to id
            ALTER TABLE accounts_user RENAME COLUMN id_new TO id;
            -- Add primary key back
            ALTER TABLE accounts_user ADD PRIMARY KEY (id);
            """,
            reverse_sql="""
            ALTER TABLE accounts_user DROP CONSTRAINT accounts_user_pkey;
            ALTER TABLE accounts_user ADD COLUMN id_old bigint DEFAULT nextval('accounts_user_id_seq'::regclass);
            UPDATE accounts_user SET id_old = nextval('accounts_user_id_seq'::regclass);
            ALTER TABLE accounts_user DROP COLUMN id;
            ALTER TABLE accounts_user RENAME COLUMN id_old TO id;
            ALTER TABLE accounts_user ADD PRIMARY KEY (id);
            """,
        ),
        migrations.AlterField(
            model_name="user",
            name="tenant_role",
            field=models.CharField(
                choices=[("admin", "Administrator"), ("member", "Member")],
                default="member",
                help_text="Role within the tenant",
                max_length=20,
            ),
        ),
    ]
