# Generated by Django 5.2.13 on 2026-04-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id_alter_user_tenant_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether MFA is enabled for this user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="MFA method: email, totp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(
                blank=True, default="", help_text="MFA secret for TOTP", max_length=64
            ),
        ),
    ]
