# Generated by Django 6.0.4 on 2026-04-28 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique tenant identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant name (organization/company name)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Professional'), ('enterprise', 'Enterprise')], default='free', help_text='Subscription plan type', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='active', help_text='Current tenant status', max_length=20)),
                ('max_proxies', models.PositiveIntegerField(default=5, help_text='Maximum number of proxies allowed')),
                ('max_repositories', models.PositiveIntegerField(default=3, help_text='Maximum number of storage repositories allowed')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Maximum storage in GB')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Maximum number of users allowed')),
                ('max_backup_tasks', models.PositiveIntegerField(default=50, help_text='Maximum concurrent backup tasks')),
                ('contact_email', models.EmailField(help_text='Primary contact email for this tenant', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, null=True)),
                ('settings', models.JSONField(default=dict, help_text='Tenant-specific settings and configurations')),
                ('logo_url', models.URLField(blank=True, help_text='URL to tenant logo image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Trial period end date', null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, help_text='Subscription end date', null=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants_tenant',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('role', models.CharField(default='member', help_text='Role to assign to the user', max_length=20)),
                ('token', models.CharField(default='4dbbb0acd51d87769463664b1c9e7147bc0980fb23d00b9fb3bb228a3559064a', help_text='Unique token for accepting the invitation', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', help_text='Current status of the invitation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant the invitation is for', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Invitation',
                'verbose_name_plural': 'Tenant Invitations',
                'db_table': 'tenants_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'tenant'], name='tenants_inv_email_5e9b66_idx'), models.Index(fields=['token'], name='tenants_inv_token_9e2edb_idx')],
            },
        ),
    ]
