# Generated by Django 6.0.4 on 2026-04-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token',
            field=models.CharField(default='234efe07e6b5d5e17836f8edaac17715d9d3f2669e823524df389a6cf3515663', help_text='Unique token for accepting the invitation', max_length=64, unique=True),
        ),
    ]
