# Generated by Django 6.0.4 on 2026-04-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_tenant_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token',
            field=models.CharField(default='5b383bea854c61a1aa0c38c374ce11418e31946a84cd20dc590b42c837010f16', help_text='Unique token for accepting the invitation', max_length=64, unique=True),
        ),
    ]
