# Generated by Django 6.0.4 on 2026-04-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_simplify_license_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token',
            field=models.CharField(default='94475aec53c2abecbae9328cad305811b8a739f9069bc4383f215f506489c633', help_text='Unique token for accepting the invitation', max_length=64, unique=True),
        ),
    ]
