# Generated by Django 6.0.4 on 2026-04-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token',
            field=models.CharField(default='b1032dc66490400c68d194a1537caecc82ab5c5233e5524e3bf67e8a2d9f871f', help_text='Unique token for accepting the invitation', max_length=64, unique=True),
        ),
    ]
