# Generated by Django 5.2.14 on 2026-05-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_add_tenant_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantinvitation",
            name="token",
            field=models.CharField(
                default="df9812b9522ebbe7063c7fd8769bcc7d1983fc9ca8b79d6d776c889ac29de271",
                help_text="Unique token for accepting the invitation",
                max_length=64,
                unique=True,
            ),
        ),
    ]
