# Generated by Django 5.2.14 on 2026-06-02 17:16

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenantinvitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantinvitation',
            name='token',
            field=models.CharField(default=tenants.models.generate_invitation_token, help_text='Unique token for accepting the invitation', max_length=64, unique=True),
        ),
    ]
