# Generated by Django 5.2.14 on 2026-05-06 05:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0006_alter_tenantinvitation_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the gateway",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the gateway",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the gateway"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname or IP address of the gateway",
                        max_length=255,
                    ),
                ),
                (
                    "internal_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Internal IP address of the gateway",
                        null=True,
                    ),
                ),
                (
                    "ssh_port",
                    models.IntegerField(
                        default=22, help_text="SSH port for remote access"
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        help_text="API token for gateway authentication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        default="Ubuntu 22.04",
                        help_text="OS version (always Ubuntu 22.04 for gateways)",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Gateway software version", max_length=50
                    ),
                ),
                (
                    "kopia_version",
                    models.CharField(
                        blank=True,
                        help_text="Kopia version installed on gateway",
                        max_length=50,
                    ),
                ),
                (
                    "cpu_cores",
                    models.IntegerField(
                        blank=True, help_text="Number of CPU cores", null=True
                    ),
                ),
                (
                    "memory_total",
                    models.BigIntegerField(
                        blank=True, help_text="Total memory in bytes", null=True
                    ),
                ),
                (
                    "disk_total",
                    models.BigIntegerField(
                        blank=True, help_text="Total disk space in bytes", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Installation"),
                            ("installing", "Installing"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="pending",
                        help_text="Current status of the gateway",
                        max_length=20,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last heartbeat timestamp from the gateway",
                        null=True,
                    ),
                ),
                (
                    "heartbeat_interval",
                    models.IntegerField(
                        default=10, help_text="Expected heartbeat interval in seconds"
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        blank=True, help_text="Current CPU usage percentage", null=True
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True,
                        help_text="Current memory usage percentage",
                        null=True,
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        blank=True, help_text="Current disk usage percentage", null=True
                    ),
                ),
                (
                    "active_mounts",
                    models.IntegerField(
                        default=0, help_text="Number of active Kopia mounts"
                    ),
                ),
                (
                    "mount_base_path",
                    models.CharField(
                        default="/mnt/kopia",
                        help_text="Base path for Kopia mounts",
                        max_length=255,
                    ),
                ),
                (
                    "max_concurrent_mounts",
                    models.IntegerField(
                        default=10, help_text="Maximum concurrent mounts allowed"
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(default=dict, help_text="Gateway capabilities"),
                ),
                (
                    "ai_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether AI Insights is enabled on this gateway",
                    ),
                ),
                (
                    "indexer_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of the indexer service",
                        max_length=20,
                    ),
                ),
                (
                    "last_index_time",
                    models.DateTimeField(
                        blank=True, help_text="Last time data was indexed", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=dict, help_text="Custom tags for organization"
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=list, help_text="Labels for categorization"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional gateway metadata"
                    ),
                ),
                (
                    "network_interfaces",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Network interface information",
                    ),
                ),
                (
                    "network_bytes_sent",
                    models.BigIntegerField(
                        default=0, help_text="Total network bytes sent"
                    ),
                ),
                (
                    "network_bytes_recv",
                    models.BigIntegerField(
                        default=0, help_text="Total network bytes received"
                    ),
                ),
                (
                    "install_token",
                    models.CharField(
                        blank=True,
                        help_text="One-time installation token",
                        max_length=64,
                    ),
                ),
                (
                    "install_token_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the install token has been used",
                    ),
                ),
                (
                    "install_command",
                    models.TextField(
                        blank=True, help_text="Generated installation command"
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the gateway was installed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the gateway first connected",
                        null=True,
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the installation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_gateways",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this gateway",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_gateways",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenant this gateway belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateways",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway",
                "verbose_name_plural": "Gateways",
                "db_table": "gateways_gateway",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="gateways_ga_status_948594_idx"
                    ),
                    models.Index(fields=["name"], name="gateways_ga_name_d69d5b_idx"),
                ],
            },
        ),
    ]
