# Generated by Django 5.2.14 on 2026-05-07 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateways", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewayHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this heartbeat was received"
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        blank=True,
                        help_text="CPU usage percentage at this heartbeat",
                        null=True,
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True,
                        help_text="Memory usage percentage at this heartbeat",
                        null=True,
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        blank=True,
                        help_text="Disk usage percentage at this heartbeat",
                        null=True,
                    ),
                ),
                (
                    "active_mounts",
                    models.IntegerField(
                        default=0, help_text="Number of active mounts at this heartbeat"
                    ),
                ),
                (
                    "network_bytes_sent",
                    models.BigIntegerField(
                        default=0, help_text="Network bytes sent since last heartbeat"
                    ),
                ),
                (
                    "network_bytes_recv",
                    models.BigIntegerField(
                        default=0,
                        help_text="Network bytes received since last heartbeat",
                    ),
                ),
                (
                    "load_average",
                    models.JSONField(
                        blank=True,
                        help_text="System load average (1, 5, 15 min)",
                        null=True,
                    ),
                ),
                (
                    "process_count",
                    models.IntegerField(
                        blank=True, help_text="Number of running processes", null=True
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        help_text="Gateway this heartbeat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="gateways.gateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway Heartbeat",
                "verbose_name_plural": "Gateway Heartbeats",
                "db_table": "gateways_heartbeat",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["gateway", "-timestamp"],
                        name="gateways_he_gateway_a0cd66_idx",
                    )
                ],
            },
        ),
    ]
