# Generated by Django 5.2.14 on 2026-05-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gateways", "0002_gatewayheartbeat"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="index_status",
            field=models.CharField(
                blank=True,
                default="idle",
                help_text="Indexing status (idle/indexing/completed/error)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="index_total_files",
            field=models.BigIntegerField(default=0, help_text="Total files to index"),
        ),
        migrations.AddField(
            model_name="gateway",
            name="indexed_files",
            field=models.BigIntegerField(
                default=0, help_text="Number of indexed files"
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="kopia_server_port",
            field=models.IntegerField(default=51515, help_text="Kopia server port"),
        ),
        migrations.AddField(
            model_name="gateway",
            name="kopia_server_status",
            field=models.CharField(
                default="stopped",
                help_text="Kopia server status (running/stopped)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="kopia_server_tls",
            field=models.BooleanField(
                default=True, help_text="Whether TLS is enabled for Kopia server"
            ),
        ),
    ]
