# Generated by Django 5.2.14 on 2026-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0003_gateway_index_status_gateway_index_total_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayheartbeat',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed heartbeat metrics payload'),
        ),
    ]
