# Generated by Django 5.2.14 on 2026-05-09 02:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup_tasks', '0002_add_tenant_to_models'),
        ('nodes', '0010_remove_alertrule_proxies_delete_alert_and_more'),
        ('repository', '0004_repository_auto_cleanup_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rule name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('alert_type', models.CharField(help_text='Type of alert this rule triggers', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('fatal', 'Fatal')], default='warning', help_text='Alert severity', max_length=20)),
                ('condition', models.JSONField(default=dict, help_text='Alert conditions (JSON format)')),
                ('applies_to_all_entities', models.BooleanField(default=True, help_text='Whether rule applies to all entities')),
                ('entity_type', models.CharField(blank=True, help_text='Type of entity this rule applies to', max_length=50)),
                ('target_ids', models.JSONField(blank=True, default=list, help_text='List of entity IDs this rule applies to')),
                ('threshold_value', models.FloatField(blank=True, help_text='Threshold value', null=True)),
                ('threshold_operator', models.CharField(choices=[('>', 'Greater than'), ('>=', 'Greater than or equal'), ('<', 'Less than'), ('<=', 'Less than or equal'), ('==', 'Equal to'), ('!=', 'Not equal to')], default='>=', help_text='Threshold comparison operator', max_length=10)),
                ('evaluation_interval', models.IntegerField(default=60, help_text='How often to evaluate this rule (seconds)')),
                ('cooldown_period', models.IntegerField(default=300, help_text='Minimum time between alerts for this rule (seconds)')),
                ('notification_enabled', models.BooleanField(default=True, help_text='Whether to send notifications for this rule')),
                ('notification_channels', models.JSONField(blank=True, default=list, help_text='Notification channels (email, slack, webhook, etc.)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this rule is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='Last time this rule triggered an alert', null=True)),
                ('source', models.CharField(blank=True, help_text='Source module/service for this rule', max_length=100)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'db_table': 'alerts_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique alert identifier', primary_key=True, serialize=False)),
                ('alert_type', models.CharField(db_index=True, help_text='Type of alert (e.g., "node_offline", "task_failed")', max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('fatal', 'Fatal')], db_index=True, default='warning', help_text='Alert severity level', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('silenced', 'Silenced')], db_index=True, default='active', help_text='Alert status', max_length=20)),
                ('entity_type', models.CharField(blank=True, help_text='Type of related entity (e.g., "nodes.ProxyNode", "backup_tasks.BackupTask")', max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, db_index=True, help_text='ID of related entity', max_length=255, null=True)),
                ('entity_name', models.CharField(blank=True, help_text='Human-readable name of related entity', max_length=255)),
                ('title', models.CharField(help_text='Alert title', max_length=255)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional alert details (JSON format)')),
                ('metric_value', models.FloatField(blank=True, help_text='Metric value that triggered the alert', null=True)),
                ('threshold_value', models.FloatField(blank=True, help_text='Threshold value that was exceeded', null=True)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the alert was triggered')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the alert was resolved', null=True)),
                ('acknowledgment_note', models.TextField(blank=True, help_text='Note added when acknowledging the alert')),
                ('resolution_note', models.TextField(blank=True, help_text='Note added when resolving the alert')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether notification was sent')),
                ('notification_channels', models.JSONField(blank=True, default=list, help_text='Channels where notification was sent')),
                ('silenced_until', models.DateTimeField(blank=True, help_text='Alert is silenced until this time', null=True)),
                ('occurrence_count', models.IntegerField(default=1, help_text='Number of times this alert has occurred')),
                ('first_occurrence_at', models.DateTimeField(blank=True, help_text='First time this alert occurred', null=True)),
                ('last_occurrence_at', models.DateTimeField(blank=True, help_text='Most recent occurrence of this alert', null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the alert (e.g., "nodes", "backup_tasks", "api")', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('backup_task', models.ForeignKey(blank=True, help_text='Related backup task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='backup_tasks.backuptask')),
                ('proxy', models.ForeignKey(blank=True, help_text='Related proxy node (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nodes.proxynode')),
                ('repository', models.ForeignKey(blank=True, help_text='Related repository (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='repository.repository')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('silenced_by', models.ForeignKey(blank=True, help_text='User who silenced the alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='silenced_alerts', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='Related task (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nodes.proxytask')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts_alert',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert_type', 'status'], name='alerts_aler_alert_t_82e8cd_idx'), models.Index(fields=['severity', 'status'], name='alerts_aler_severit_12d0e1_idx'), models.Index(fields=['source'], name='alerts_aler_source_5b6ed7_idx'), models.Index(fields=['entity_type', 'entity_id'], name='alerts_aler_entity__4bdfb3_idx'), models.Index(fields=['triggered_at'], name='alerts_aler_trigger_5b4eb6_idx')],
            },
        ),
    ]
