# Generated by Codex for the global alert center redesign.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_enhance_alert_rules_and_channels"),
    ]

    operations = [
        migrations.DeleteModel(name="AlertChannelHistory"),
        migrations.DeleteModel(name="SystemMetric"),
        migrations.DeleteModel(name="AlertChannel"),
        migrations.DeleteModel(name="Alert"),
        migrations.DeleteModel(name="AlertRule"),
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS notification_logs",
                "DROP TABLE IF EXISTS notification_channels",
                "DROP TABLE IF EXISTS alert_records",
                "DROP TABLE IF EXISTS alert_policies",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="AlertPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(choices=[("metric", "Metric Alert"), ("availability", "Availability Alert"), ("job", "Job Alert"), ("event", "Event Alert"), ("system", "System Alert")], max_length=50)),
                ("severity", models.CharField(choices=[("critical", "Critical"), ("warning", "Warning"), ("info", "Info")], max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("resource_type", models.CharField(blank=True, choices=[("sync_proxy", "Sync Proxy"), ("gateway", "Gateway"), ("agent_proxy", "Agent Proxy"), ("backup_repository", "Backup Repository"), ("source_resource", "Source Resource"), ("target_storage", "Target Storage"), ("job", "Job"), ("system_service", "System Service"), ("license", "License"), ("user", "User")], max_length=100, null=True)),
                ("scope", models.CharField(choices=[("all", "All"), ("selected", "Selected")], default="selected", max_length=50)),
                ("resource_ids", models.JSONField(blank=True, default=list)),
                ("trigger_rule", models.JSONField()),
                ("recovery_rule", models.JSONField(blank=True, null=True)),
                ("notification_channel_ids", models.JSONField(blank=True, default=list)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alert_policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("policy_id", models.UUIDField(blank=True, null=True)),
                ("type", models.CharField(choices=[("metric", "Metric Alert"), ("availability", "Availability Alert"), ("job", "Job Alert"), ("event", "Event Alert"), ("system", "System Alert")], max_length=50)),
                ("severity", models.CharField(choices=[("critical", "Critical"), ("warning", "Warning"), ("info", "Info")], max_length=50)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("firing", "Firing"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved")], max_length=50)),
                ("resource_type", models.CharField(blank=True, choices=[("sync_proxy", "Sync Proxy"), ("gateway", "Gateway"), ("agent_proxy", "Agent Proxy"), ("backup_repository", "Backup Repository"), ("source_resource", "Source Resource"), ("target_storage", "Target Storage"), ("job", "Job"), ("system_service", "System Service"), ("license", "License"), ("user", "User")], max_length=100, null=True)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("resource_name", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                ("current_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("threshold_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("fingerprint", models.CharField(db_index=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("first_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_by", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alert_records",
                "ordering": ["-last_triggered_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("email", "Email"), ("webhook", "Webhook"), ("dingtalk", "DingTalk"), ("wecom", "WeCom")], max_length=50)),
                ("enabled", models.BooleanField(default=True)),
                ("config", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_channels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("alert_record_id", models.UUIDField()),
                ("channel_id", models.UUIDField()),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed")], max_length=50)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("cpu", models.JSONField(blank=True, default=dict)),
                ("memory", models.JSONField(blank=True, default=dict)),
                ("swap", models.JSONField(blank=True, default=dict)),
                ("disks", models.JSONField(blank=True, default=list)),
                ("disk_io", models.JSONField(blank=True, default=list)),
                ("networks", models.JSONField(blank=True, default=list)),
                ("load_average", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "alerts_system_metric",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(model_name="alertrecord", index=models.Index(fields=["status"], name="idx_alert_records_status")),
        migrations.AddIndex(model_name="alertrecord", index=models.Index(fields=["type"], name="idx_alert_records_type")),
        migrations.AddIndex(model_name="alertrecord", index=models.Index(fields=["severity"], name="idx_alert_records_severity")),
        migrations.AddIndex(model_name="alertrecord", index=models.Index(fields=["fingerprint"], name="idx_alert_records_fingerprint")),
        migrations.AddIndex(model_name="alertpolicy", index=models.Index(fields=["enabled"], name="idx_alert_policies_enabled")),
        migrations.AddIndex(model_name="alertpolicy", index=models.Index(fields=["type"], name="idx_alert_policies_type")),
    ]
