# Generated by Django 5.2.13 on 2026-04-22 16:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the node', unique=True)),
                ('name', models.CharField(help_text='Display name for the node', max_length=255, unique=True)),
                ('node_type', models.CharField(choices=[('source_proxy', 'Source Proxy'), ('target_gateway', 'Target Gateway')], help_text='Type of node (source proxy or target gateway)', max_length=20)),
                ('hostname', models.CharField(help_text='Hostname or IP address of the node', max_length=255)),
                ('port', models.IntegerField(default=8080, help_text='Port number for node communication')),
                ('protocol', models.CharField(default='https', help_text='Protocol for node communication (http/https)', max_length=10)),
                ('api_key', models.CharField(help_text='API key for node authentication', max_length=64, unique=True)),
                ('api_secret', models.CharField(blank=True, help_text='API secret for node authentication (encrypted)', max_length=128)),
                ('operating_system', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('macos', 'macOS')], help_text='Operating system of the node', max_length=20)),
                ('version', models.CharField(blank=True, help_text='Node software version', max_length=50)),
                ('cpu_cores', models.IntegerField(blank=True, help_text='Number of CPU cores', null=True)),
                ('memory_total', models.BigIntegerField(blank=True, help_text='Total memory in bytes', null=True)),
                ('disk_total', models.BigIntegerField(blank=True, help_text='Total disk space in bytes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='pending', help_text='Current status of the node', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, help_text='Last heartbeat timestamp from the node', null=True)),
                ('heartbeat_interval', models.IntegerField(default=30, help_text='Expected heartbeat interval in seconds')),
                ('capabilities', models.JSONField(default=dict, help_text='Node capabilities and supported features')),
                ('tags', models.JSONField(default=dict, help_text='Custom tags for organization')),
                ('metadata', models.JSONField(default=dict, help_text='Additional node metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(blank=True, help_text='When the node was registered and activated', null=True)),
                ('owner', models.ForeignKey(help_text='User who owns this node', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'db_table': 'nodes_node',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceProxyNode',
            fields=[
            ],
            options={
                'verbose_name': 'Source Proxy Node',
                'verbose_name_plural': 'Source Proxy Nodes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nodes.node',),
        ),
        migrations.CreateModel(
            name='TargetGatewayNode',
            fields=[
            ],
            options={
                'verbose_name': 'Target Gateway Node',
                'verbose_name_plural': 'Target Gateway Nodes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nodes.node',),
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, help_text='Unique connection identifier')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', help_text='Connection status', max_length=20)),
                ('remote_address', models.GenericIPAddressField(blank=True, help_text='Remote client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent')),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Connection start time')),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='Connection end time', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Last message received/sent time', null=True)),
                ('message_count', models.BigIntegerField(default=0, help_text='Total messages exchanged')),
                ('node', models.ForeignKey(help_text='Connected node', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node Connection',
                'verbose_name_plural': 'Node Connections',
                'db_table': 'nodes_connection',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Heartbeat timestamp')),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage', null=True)),
                ('disk_usage', models.FloatField(blank=True, help_text='Disk usage percentage', null=True)),
                ('network_in', models.BigIntegerField(blank=True, help_text='Network bytes received', null=True)),
                ('network_out', models.BigIntegerField(blank=True, help_text='Network bytes sent', null=True)),
                ('active_tasks', models.IntegerField(default=0, help_text='Number of active tasks on the node')),
                ('metadata', models.JSONField(default=dict, help_text='Additional heartbeat metadata')),
                ('node', models.ForeignKey(help_text='Node that sent this heartbeat', on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node Heartbeat',
                'verbose_name_plural': 'Node Heartbeats',
                'db_table': 'nodes_heartbeat',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NodeTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(help_text='Unique identifier of the assigned task')),
                ('task_type', models.CharField(help_text='Type of task (backup, recovery, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Assignment status', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the task was assigned')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the node accepted the task', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the task execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task completed', null=True)),
                ('progress', models.IntegerField(default=0, help_text='Task progress percentage (0-100)')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Task execution result')),
                ('error', models.TextField(blank=True, help_text='Error message if task failed')),
                ('node', models.ForeignKey(help_text='Node assigned to execute the task', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='nodes.node')),
            ],
            options={
                'verbose_name': 'Node Task Assignment',
                'verbose_name_plural': 'Node Task Assignments',
                'db_table': 'nodes_task_assignment',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_id'], name='nodes_node_node_id_ef6689_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['name'], name='nodes_node_name_cc1254_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='nodes_node_node_ty_c259da_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['status'], name='nodes_node_status_92bac2_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeconnection',
            index=models.Index(fields=['node', 'status'], name='nodes_conne_node_id_c7ddde_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeconnection',
            index=models.Index(fields=['connection_id'], name='nodes_conne_connect_971885_idx'),
        ),
        migrations.AddIndex(
            model_name='nodeheartbeat',
            index=models.Index(fields=['node', '-timestamp'], name='nodes_heart_node_id_c9b4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='nodetaskassignment',
            index=models.Index(fields=['task_id'], name='nodes_task__task_id_1e8a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='nodetaskassignment',
            index=models.Index(fields=['node', 'status'], name='nodes_task__node_id_f2f1d0_idx'),
        ),
    ]
