# Generated by Django 5.2.13 on 2026-04-27 11:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Heartbeat timestamp",
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        blank=True, help_text="CPU usage percentage", null=True
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True, help_text="Memory usage percentage", null=True
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        blank=True, help_text="Disk usage percentage", null=True
                    ),
                ),
                (
                    "network_in",
                    models.BigIntegerField(
                        blank=True, help_text="Network bytes received", null=True
                    ),
                ),
                (
                    "network_out",
                    models.BigIntegerField(
                        blank=True, help_text="Network bytes sent", null=True
                    ),
                ),
                (
                    "active_tasks",
                    models.IntegerField(default=0, help_text="Number of active tasks"),
                ),
                (
                    "completed_tasks",
                    models.IntegerField(
                        default=0,
                        help_text="Number of completed tasks since last heartbeat",
                    ),
                ),
                (
                    "failed_tasks",
                    models.IntegerField(
                        default=0,
                        help_text="Number of failed tasks since last heartbeat",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional heartbeat metadata"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy Heartbeat",
                "verbose_name_plural": "Proxy Heartbeats",
                "db_table": "nodes_proxy_heartbeat",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NodeHeartbeat",
            fields=[],
            options={
                "verbose_name": "Node Heartbeat (Legacy)",
                "verbose_name_plural": "Node Heartbeats (Legacy)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("nodes.proxyheartbeat",),
        ),
        migrations.CreateModel(
            name="ProxyNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the proxy",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the proxy",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("agent", "Agent Proxy"), ("sync", "Sync Proxy")],
                        default="agent",
                        help_text="Proxy role: agent (source-side) or sync (collector)",
                        max_length=10,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True,
                        help_text="Hostname or IP address of the proxy",
                        max_length=255,
                    ),
                ),
                (
                    "internal_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Internal IP address of the proxy",
                        null=True,
                    ),
                ),
                (
                    "api_token",
                    models.CharField(
                        help_text="API token for proxy authentication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("windows", "Windows"),
                            ("linux", "Linux"),
                            ("macos", "macOS"),
                        ],
                        help_text="Operating system of the proxy",
                        max_length=20,
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, help_text="OS version details", max_length=100
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Proxy software version", max_length=50
                    ),
                ),
                (
                    "kopia_version",
                    models.CharField(
                        blank=True,
                        help_text="Kopia version installed on proxy",
                        max_length=50,
                    ),
                ),
                (
                    "cpu_cores",
                    models.IntegerField(
                        blank=True, help_text="Number of CPU cores", null=True
                    ),
                ),
                (
                    "memory_total",
                    models.BigIntegerField(
                        blank=True, help_text="Total memory in bytes", null=True
                    ),
                ),
                (
                    "disk_total",
                    models.BigIntegerField(
                        blank=True, help_text="Total disk space in bytes", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Installation"),
                            ("installing", "Installing"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="pending",
                        help_text="Current status of the proxy",
                        max_length=20,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last heartbeat timestamp from the proxy",
                        null=True,
                    ),
                ),
                (
                    "heartbeat_interval",
                    models.IntegerField(
                        default=10, help_text="Expected heartbeat interval in seconds"
                    ),
                ),
                (
                    "cpu_usage",
                    models.FloatField(
                        blank=True, help_text="Current CPU usage percentage", null=True
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True,
                        help_text="Current memory usage percentage",
                        null=True,
                    ),
                ),
                (
                    "disk_usage",
                    models.FloatField(
                        blank=True, help_text="Current disk usage percentage", null=True
                    ),
                ),
                (
                    "active_tasks",
                    models.IntegerField(default=0, help_text="Number of active tasks"),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        default=dict,
                        help_text="Proxy capabilities (mount_types, backup_types, etc.)",
                    ),
                ),
                (
                    "mount_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Supported mount types for Sync Proxy (nfs, smb, etc.)",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=dict, help_text="Custom tags for organization"
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=list, help_text="Labels for categorization"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional proxy metadata"
                    ),
                ),
                (
                    "install_token",
                    models.CharField(
                        blank=True,
                        help_text="One-time installation token",
                        max_length=64,
                    ),
                ),
                (
                    "install_token_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the install token has been used",
                    ),
                ),
                (
                    "install_command",
                    models.TextField(
                        blank=True, help_text="Generated installation command"
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the proxy was installed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the proxy first connected",
                        null=True,
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the installation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_proxies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this proxy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_proxies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy",
                "verbose_name_plural": "Proxies",
                "db_table": "nodes_proxy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="proxyheartbeat",
            name="proxy",
            field=models.ForeignKey(
                help_text="Proxy that sent this heartbeat",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heartbeats",
                to="nodes.proxynode",
            ),
        ),
        migrations.CreateModel(
            name="NodeConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_id",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Unique connection identifier"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="connected",
                        help_text="Connection status",
                        max_length=20,
                    ),
                ),
                (
                    "remote_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Remote client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Client user agent"),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Connection start time",
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, help_text="Connection end time", null=True
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last message received/sent time",
                        null=True,
                    ),
                ),
                (
                    "message_count",
                    models.BigIntegerField(
                        default=0, help_text="Total messages exchanged"
                    ),
                ),
                (
                    "proxy",
                    models.ForeignKey(
                        help_text="Connected proxy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="nodes.proxynode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy Connection",
                "verbose_name_plural": "Proxy Connections",
                "db_table": "nodes_connection",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[],
            options={
                "verbose_name": "Node (Legacy)",
                "verbose_name_plural": "Nodes (Legacy)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("nodes.proxynode",),
        ),
        migrations.CreateModel(
            name="ProxyTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("backup", "Backup"),
                            ("restore", "Restore"),
                            ("mount", "Mount"),
                            ("unmount", "Unmount"),
                            ("snapshot_list", "Snapshot List"),
                            ("verify", "Verify"),
                        ],
                        help_text="Type of task",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        help_text="Task status",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, help_text="Task parameters"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispatched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When task was dispatched to proxy",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When task execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When task completed", null=True
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(
                        default=3600, help_text="Task timeout in seconds"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Task progress percentage (0-100)"
                    ),
                ),
                (
                    "progress_message",
                    models.TextField(blank=True, help_text="Progress status message"),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, help_text="Task execution result"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if task failed"
                    ),
                ),
                (
                    "repository_id",
                    models.UUIDField(
                        blank=True, help_text="Related repository ID", null=True
                    ),
                ),
                (
                    "source_resource_id",
                    models.UUIDField(
                        blank=True, help_text="Related source resource ID", null=True
                    ),
                ),
                (
                    "proxy",
                    models.ForeignKey(
                        help_text="Proxy assigned to execute the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="nodes.proxynode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proxy Task",
                "verbose_name_plural": "Proxy Tasks",
                "db_table": "nodes_proxy_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="proxynode",
            index=models.Index(fields=["role"], name="nodes_proxy_role_6ff65f_idx"),
        ),
        migrations.AddIndex(
            model_name="proxynode",
            index=models.Index(fields=["status"], name="nodes_proxy_status_2fb4bc_idx"),
        ),
        migrations.AddIndex(
            model_name="proxynode",
            index=models.Index(fields=["name"], name="nodes_proxy_name_385dab_idx"),
        ),
        migrations.AddIndex(
            model_name="proxyheartbeat",
            index=models.Index(
                fields=["proxy", "-timestamp"], name="nodes_proxy_proxy_i_ba514d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["proxy", "status"], name="nodes_conne_proxy_i_3fed1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nodeconnection",
            index=models.Index(
                fields=["connection_id"], name="nodes_conne_connect_971885_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proxytask",
            index=models.Index(
                fields=["proxy", "status"], name="nodes_proxy_proxy_i_fb3b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proxytask",
            index=models.Index(
                fields=["task_type", "status"], name="nodes_proxy_task_ty_04598f_idx"
            ),
        ),
    ]
