# Generated by Django 5.2.13 on 2026-04-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="target_os",
            field=models.CharField(
                choices=[
                    ("windows", "Windows"),
                    ("linux", "Linux"),
                    ("macos", "macOS"),
                ],
                default="linux",
                help_text="Target operating system for installation",
                max_length=20,
            ),
        ),
    ]
