# Generated by Django 5.2.13 on 2026-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_proxynode_target_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="network_bytes_recv",
            field=models.BigIntegerField(
                default=0, help_text="Total network bytes received"
            ),
        ),
        migrations.AddField(
            model_name="proxynode",
            name="network_bytes_sent",
            field=models.BigIntegerField(
                default=0, help_text="Total network bytes sent"
            ),
        ),
        migrations.AddField(
            model_name="proxynode",
            name="network_interfaces",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Network interface information (name, IP, MAC, bytes in/out)",
            ),
        ),
    ]
