# Generated by Django 6.0.4 on 2026-04-28 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_add_network_fields'),
        ('tenants', '0002_add_tenant_to_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proxynode',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this proxy belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns this proxy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_proxies', to=settings.AUTH_USER_MODEL),
        ),
    ]
