# Generated by Django 5.2.14 on 2026-05-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0004_add_tenant_to_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxytask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("backup", "Backup"),
                    ("restore", "Restore"),
                    ("mount", "Mount"),
                    ("unmount", "Unmount"),
                    ("snapshot_list", "Snapshot List"),
                    ("verify", "Verify"),
                    ("test_storage", "Test Storage"),
                    ("init_repository", "Init Repository"),
                ],
                help_text="Type of task",
                max_length=20,
            ),
        ),
    ]
