# Generated by Django 5.2.14 on 2026-05-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_update_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxynode',
            name='bandwidth_limit_kbps',
            field=models.IntegerField(blank=True, help_text='Default bandwidth limit in KB/s (0 = no limit)', null=True),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='health_score',
            field=models.IntegerField(default=100, help_text='Health score (0-100, higher is better)'),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', help_text='Overall health status', max_length=20),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='last_health_check',
            field=models.DateTimeField(blank=True, help_text='Last health check timestamp', null=True),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='max_concurrent_tasks',
            field=models.IntegerField(default=3, help_text='Maximum number of concurrent tasks allowed'),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='total_data_backed_up',
            field=models.BigIntegerField(default=0, help_text='Total data backed up in bytes'),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='total_tasks_completed',
            field=models.IntegerField(default=0, help_text='Total number of tasks completed'),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='total_tasks_failed',
            field=models.IntegerField(default=0, help_text='Total number of tasks failed'),
        ),
        migrations.AddField(
            model_name='proxynode',
            name='uptime_seconds',
            field=models.BigIntegerField(default=0, help_text='Total uptime in seconds'),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='current_file',
            field=models.CharField(blank=True, help_text='Current file being processed', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='eta',
            field=models.CharField(blank=True, help_text='Estimated time remaining', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='processed_bytes',
            field=models.BigIntegerField(default=0, help_text='Number of bytes processed'),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='processed_files',
            field=models.IntegerField(default=0, help_text='Number of files processed'),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='speed_mbps',
            field=models.FloatField(default=0.0, help_text='Current processing speed in MB/s'),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='total_bytes',
            field=models.BigIntegerField(default=0, help_text='Total bytes to process'),
        ),
        migrations.AddField(
            model_name='proxytask',
            name='total_files',
            field=models.IntegerField(default=0, help_text='Total number of files to process'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Installation'), ('installing', 'Installing'), ('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='pending', help_text='Current status of the proxy', max_length=20),
        ),
    ]
