# Generated by Django 5.2.14 on 2026-05-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_proxynode_bandwidth_limit_kbps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxytask',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When task was accepted by proxy', null=True),
        ),
    ]
