# Generated by Django 5.2.14 on 2026-05-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_alertrule_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrule',
            name='proxies',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
    ]
