# Generated by Django 5.2.14 on 2026-05-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0011_proxy_metrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proxymetrics",
            name="proxy",
        ),
        migrations.DeleteModel(
            name="MetricsAggregation",
        ),
        migrations.DeleteModel(
            name="ProxyMetrics",
        ),
    ]
