# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_add_snapshot_export_task_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proxytask',
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(('repository_id__isnull', False))
                    & models.Q(('status__in', ['pending', 'dispatched', 'accepted', 'running']))
                    & models.Q(('task_type__in', [
                        'snapshot_delete',
                        'kopia_maintenance',
                        'init_repository',
                    ]))
                ),
                fields=('repository_id',),
                name='unique_active_exclusive_repository_task',
            ),
        ),
        migrations.AddConstraint(
            model_name='proxytask',
            constraint=models.UniqueConstraint(
                condition=(
                    models.Q(('repository_id__isnull', False))
                    & models.Q(('source_resource_id__isnull', False))
                    & models.Q(('status__in', ['pending', 'dispatched', 'accepted', 'running']))
                    & models.Q(('task_type__in', ['backup', 'snapshot_list']))
                ),
                fields=('repository_id', 'source_resource_id'),
                name='unique_active_repository_source_task',
            ),
        ),
    ]
