# Generated by Django 5.2.13 on 2026-04-22 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('policies', '0001_initial'),
        ('repository', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Task name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Task description')),
                ('task_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('differential', 'Differential Backup')], default='full', help_text='Type of backup', max_length=20)),
                ('paths', models.JSONField(default=list, help_text='List of paths to backup')),
                ('exclude_patterns', models.JSONField(blank=True, default=list, help_text='Patterns to exclude from backup')),
                ('compression_enabled', models.BooleanField(default=True, help_text='Enable compression')),
                ('encryption_enabled', models.BooleanField(default=False, help_text='Enable encryption')),
                ('next_run_time', models.DateTimeField(blank=True, help_text='Next scheduled run time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current task status', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('retention_days', models.IntegerField(default=30, help_text='Number of days to retain snapshots')),
                ('max_snapshots', models.IntegerField(default=10, help_text='Maximum number of snapshots to keep')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('backed_up_files', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('backed_up_size', models.BigIntegerField(default=0)),
                ('skipped_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(blank=True, help_text='Associated backup policy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='policies.backuppolicy')),
                ('source_node', models.ForeignKey(help_text='Source node for backup', on_delete=django.db.models.deletion.CASCADE, related_name='source_backup_tasks', to='nodes.node')),
                ('target_repository', models.ForeignKey(help_text='Target repository for backup', on_delete=django.db.models.deletion.CASCADE, related_name='backup_tasks', to='repository.repository')),
                ('user', models.ForeignKey(help_text='User who created the task', on_delete=django.db.models.deletion.CASCADE, related_name='backup_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Snapshot name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Snapshot description')),
                ('version', models.CharField(help_text='Snapshot version', max_length=50)),
                ('storage_path', models.CharField(help_text='Path in the repository', max_length=1024)),
                ('manifest_path', models.CharField(blank=True, help_text='Path to snapshot manifest', max_length=1024)),
                ('total_size', models.BigIntegerField(default=0, help_text='Total size in bytes')),
                ('file_count', models.IntegerField(default=0, help_text='Number of files in snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date', null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the snapshot', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('parent_snapshot', models.ForeignKey(blank=True, help_text='Parent snapshot for incremental backups', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_snapshots', to='backup_tasks.backupsnapshot')),
                ('repository', models.ForeignKey(help_text='Repository containing this snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='repository.repository')),
                ('task', models.ForeignKey(help_text='Parent backup task', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='backup_tasks.backuptask')),
            ],
            options={
                'db_table': 'backup_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_path', models.CharField(help_text='Original file path on source', max_length=4096)),
                ('relative_path', models.CharField(help_text='Relative path within backup', max_length=4096)),
                ('file_name', models.CharField(help_text='File name', max_length=255)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('checksum', models.CharField(help_text='MD5/SHA checksum', max_length=64)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('status', models.CharField(choices=[('backed_up', 'Backed Up'), ('modified', 'Modified'), ('deleted', 'Deleted')], default='backed_up', help_text='File backup status', max_length=20)),
                ('backed_up_at', models.DateTimeField(auto_now_add=True, help_text='When the file was backed up')),
                ('modified_at', models.DateTimeField(blank=True, help_text='Original file modification time', null=True)),
                ('snapshot', models.ForeignKey(help_text='Parent snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='backup_tasks.backupsnapshot')),
            ],
            options={
                'db_table': 'backup_files',
                'ordering': ['-backed_up_at'],
                'indexes': [models.Index(fields=['snapshot', 'relative_path'], name='backup_file_snapsho_bad57c_idx'), models.Index(fields=['checksum'], name='backup_file_checksu_c5d0ef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='backuptask',
            index=models.Index(fields=['status'], name='backup_task_status_6b22ab_idx'),
        ),
        migrations.AddIndex(
            model_name='backuptask',
            index=models.Index(fields=['source_node', 'status'], name='backup_task_source__e7408f_idx'),
        ),
        migrations.AddIndex(
            model_name='backuptask',
            index=models.Index(fields=['next_run_time'], name='backup_task_next_ru_231063_idx'),
        ),
        migrations.AddIndex(
            model_name='backupsnapshot',
            index=models.Index(fields=['task', '-created_at'], name='backup_snap_task_id_8e7ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='backupsnapshot',
            index=models.Index(fields=['expires_at'], name='backup_snap_expires_85430b_idx'),
        ),
    ]
