# Generated by Django 5.2.13 on 2026-04-27 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        ("repository", "0001_initial"),
        ("source_resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Task name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Task description"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Backup"),
                            ("incremental", "Incremental Backup"),
                            ("differential", "Differential Backup"),
                        ],
                        default="incremental",
                        help_text="Type of backup",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        help_text="Task priority",
                        max_length=10,
                    ),
                ),
                (
                    "backup_paths",
                    models.JSONField(
                        default=list,
                        help_text="List of paths to backup (relative to source)",
                    ),
                ),
                (
                    "exclude_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Patterns to exclude from backup (glob patterns)",
                    ),
                ),
                (
                    "include_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Patterns to include in backup (glob patterns)",
                    ),
                ),
                (
                    "compression_enabled",
                    models.BooleanField(default=True, help_text="Enable compression"),
                ),
                (
                    "compression_type",
                    models.CharField(
                        blank=True,
                        default="zstd",
                        help_text="Compression algorithm",
                        max_length=20,
                    ),
                ),
                (
                    "encryption_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable encryption (uses repository encryption)",
                    ),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(
                        blank=True, help_text="Next scheduled run time", null=True
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(
                        blank=True, help_text="Last run time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        help_text="Current task status",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.TextField(blank=True, help_text="Status message or details"),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        default=30, help_text="Number of days to retain snapshots"
                    ),
                ),
                (
                    "max_snapshots",
                    models.IntegerField(
                        default=10, help_text="Maximum number of snapshots to keep"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_files", models.IntegerField(default=0)),
                ("backed_up_files", models.IntegerField(default=0)),
                ("total_size", models.BigIntegerField(default=0)),
                ("backed_up_size", models.BigIntegerField(default=0)),
                ("skipped_files", models.IntegerField(default=0)),
                ("failed_files", models.IntegerField(default=0)),
                (
                    "bytes_per_second",
                    models.BigIntegerField(
                        default=0, help_text="Backup speed in bytes per second"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated backup policy/schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="policies.backuppolicy",
                    ),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source resource for backup data",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_tasks",
                        to="source_resources.sourceresource",
                    ),
                ),
                (
                    "target_repository",
                    models.ForeignKey(
                        help_text="Target repository for backup storage",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_tasks",
                        to="repository.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "backup_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Snapshot name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Snapshot description"),
                ),
                (
                    "version",
                    models.CharField(help_text="Snapshot version", max_length=50),
                ),
                (
                    "storage_path",
                    models.CharField(
                        help_text="Path in the repository", max_length=1024
                    ),
                ),
                (
                    "manifest_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to snapshot manifest",
                        max_length=1024,
                    ),
                ),
                (
                    "total_size",
                    models.BigIntegerField(default=0, help_text="Total size in bytes"),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0, help_text="Number of files in snapshot"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Expiration date", null=True
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 checksum of the snapshot",
                        max_length=128,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata"
                    ),
                ),
                (
                    "parent_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent snapshot for incremental backups",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_snapshots",
                        to="backup_tasks.backupsnapshot",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        help_text="Repository containing this snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="repository.repository",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Parent backup task",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="backup_tasks.backuptask",
                    ),
                ),
            ],
            options={
                "db_table": "backup_snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_path",
                    models.CharField(
                        help_text="Original file path on source", max_length=4096
                    ),
                ),
                (
                    "relative_path",
                    models.CharField(
                        help_text="Relative path within backup", max_length=4096
                    ),
                ),
                ("file_name", models.CharField(help_text="File name", max_length=255)),
                (
                    "size",
                    models.BigIntegerField(default=0, help_text="File size in bytes"),
                ),
                (
                    "checksum",
                    models.CharField(help_text="MD5/SHA checksum", max_length=64),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, help_text="MIME type", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backed_up", "Backed Up"),
                            ("modified", "Modified"),
                            ("deleted", "Deleted"),
                        ],
                        default="backed_up",
                        help_text="File backup status",
                        max_length=20,
                    ),
                ),
                (
                    "backed_up_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the file was backed up"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original file modification time",
                        null=True,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        help_text="Parent snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="backup_tasks.backupsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "backup_files",
                "ordering": ["-backed_up_at"],
                "indexes": [
                    models.Index(
                        fields=["snapshot", "relative_path"],
                        name="backup_file_snapsho_bad57c_idx",
                    ),
                    models.Index(
                        fields=["checksum"], name="backup_file_checksu_c5d0ef_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="backuptask",
            index=models.Index(fields=["status"], name="backup_task_status_6b22ab_idx"),
        ),
        migrations.AddIndex(
            model_name="backuptask",
            index=models.Index(
                fields=["source_resource", "status"],
                name="backup_task_source__d039cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backuptask",
            index=models.Index(
                fields=["target_repository", "status"],
                name="backup_task_target__e14e0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backuptask",
            index=models.Index(
                fields=["next_run_time"], name="backup_task_next_ru_231063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backupsnapshot",
            index=models.Index(
                fields=["task", "-created_at"], name="backup_snap_task_id_8e7ff6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backupsnapshot",
            index=models.Index(
                fields=["expires_at"], name="backup_snap_expires_85430b_idx"
            ),
        ),
    ]
