# Generated by Django 5.2.13 on 2026-04-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup_tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="backuptask",
            name="backup_task_source__e7408f_idx",
        ),
        migrations.RemoveField(
            model_name="backuptask",
            name="paths",
        ),
        migrations.RemoveField(
            model_name="backuptask",
            name="source_node",
        ),
        migrations.AddField(
            model_name="backuptask",
            name="backup_paths",
            field=models.JSONField(
                default=list, help_text="List of paths to backup (relative to source)"
            ),
        ),
        migrations.AddField(
            model_name="backuptask",
            name="bytes_per_second",
            field=models.BigIntegerField(
                default=0, help_text="Backup speed in bytes per second"
            ),
        ),
        migrations.AddField(
            model_name="backuptask",
            name="compression_type",
            field=models.CharField(
                blank=True,
                default="zstd",
                help_text="Compression algorithm",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="backuptask",
            name="include_patterns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Patterns to include in backup (glob patterns)",
            ),
        ),
        migrations.AddField(
            model_name="backuptask",
            name="last_run_time",
            field=models.DateTimeField(
                blank=True, help_text="Last run time", null=True
            ),
        ),
        migrations.AddField(
            model_name="backuptask",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                default="normal",
                help_text="Task priority",
                max_length=10,
            ),
        ),
    ]
