# Generated by Django 5.2.13 on 2026-04-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backup_tasks",
            "0002_remove_backuptask_backup_task_source__e7408f_idx_and_more",
        ),
        ("policies", "0001_initial"),
        (
            "repository",
            "0002_repository_bound_node_repository_compression_type_and_more",
        ),
        ("source_resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backuptask",
            name="source_resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Source resource for backup data",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_tasks",
                to="source_resources.sourceresource",
            ),
        ),
        migrations.AddField(
            model_name="backuptask",
            name="status_message",
            field=models.TextField(blank=True, help_text="Status message or details"),
        ),
        migrations.AlterField(
            model_name="backuptask",
            name="encryption_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable encryption (uses repository encryption)"
            ),
        ),
        migrations.AlterField(
            model_name="backuptask",
            name="exclude_patterns",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Patterns to exclude from backup (glob patterns)",
            ),
        ),
        migrations.AlterField(
            model_name="backuptask",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated backup policy/schedule",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="policies.backuppolicy",
            ),
        ),
        migrations.AlterField(
            model_name="backuptask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("paused", "Paused"),
                ],
                default="pending",
                help_text="Current task status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="backuptask",
            name="target_repository",
            field=models.ForeignKey(
                help_text="Target repository for backup storage",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_tasks",
                to="repository.repository",
            ),
        ),
        migrations.AlterField(
            model_name="backuptask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("full", "Full Backup"),
                    ("incremental", "Incremental Backup"),
                    ("differential", "Differential Backup"),
                ],
                default="incremental",
                help_text="Type of backup",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="backuptask",
            index=models.Index(
                fields=["source_resource", "status"],
                name="backup_task_source__d039cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backuptask",
            index=models.Index(
                fields=["target_repository", "status"],
                name="backup_task_target__e14e0d_idx",
            ),
        ),
    ]
