# Generated by Django 5.2.14 on 2026-05-18 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_tasks', '0006_backuptask_execution_placement'),
        ('nodes', '0014_restore_proxy_metrics'),
        ('repository', '0007_repository_kopia_password'),
        ('source_resources', '0003_source_resource_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuptask',
            name='last_run_status',
            field=models.CharField(blank=True, help_text='Status of the latest execution run', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupTaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('retry', 'Retry')], default='manual', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('processed_bytes', models.BigIntegerField(default=0)),
                ('speed_mbps', models.FloatField(default=0.0)),
                ('eta', models.CharField(blank=True, max_length=64, null=True)),
                ('current_file', models.CharField(blank=True, max_length=512, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proxy_task', models.OneToOneField(blank=True, help_text='Low-level proxy task for this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_run', to='nodes.proxytask')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to='repository.repository')),
                ('selected_proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to='nodes.proxynode')),
                ('source_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_runs', to='source_resources.sourceresource')),
                ('task', models.ForeignKey(help_text='Backup task definition for this run', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backup_tasks.backuptask')),
            ],
            options={
                'db_table': 'backup_task_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='backup_task_task_id_12e227_idx'), models.Index(fields=['status'], name='backup_task_status_ca12a0_idx'), models.Index(fields=['trigger_type'], name='backup_task_trigger_cdae0e_idx')],
            },
        ),
    ]
