# Generated by Django 5.2.13 on 2026-04-29 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            ("mfa_code", "MFA Code"),
                            ("welcome", "Welcome Email"),
                            ("notification", "General Notification"),
                        ],
                        help_text="Type of email template",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject template", max_length=255
                    ),
                ),
                ("html_body", models.TextField(help_text="HTML email body template")),
                (
                    "text_body",
                    models.TextField(
                        blank=True, help_text="Plain text email body template"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list, help_text="List of template variables"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "db_table": "email_template",
                "ordering": ["template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SMTPConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        help_text="Configuration name",
                        max_length=100,
                    ),
                ),
                (
                    "host",
                    models.CharField(help_text="SMTP server hostname", max_length=255),
                ),
                (
                    "port",
                    models.IntegerField(default=587, help_text="SMTP server port"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="SMTP authentication username",
                        max_length=255,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="SMTP authentication password (encrypted)",
                        max_length=255,
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(default=True, help_text="Use TLS encryption"),
                ),
                (
                    "use_ssl",
                    models.BooleanField(default=False, help_text="Use SSL encryption"),
                ),
                (
                    "from_email",
                    models.EmailField(
                        default="noreply@hyperfilelens.com",
                        help_text="Default sender email address",
                        max_length=254,
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        default="HyperFileLens",
                        help_text="Default sender name",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this configuration is active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default configuration",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMTP Configuration",
                "verbose_name_plural": "SMTP Configurations",
                "db_table": "smtp_config",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting key (e.g., smtp_host, smtp_port)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Setting value (can be string, JSON, etc.)",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of this setting",
                        max_length=255,
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this setting contains sensitive data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
                "ordering": ["key"],
            },
        ),
    ]
