# Generated by Django 5.2.14 on 2026-06-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
