# Generated by Django 5.2.13 on 2026-04-27 11:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the actor", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent string", max_length=500
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("access", "Access"),
                            ("execute", "Execute"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("error", "Error"),
                        ],
                        help_text="Type of action",
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        help_text="Type of resource affected", max_length=100
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected resource",
                        max_length=100,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Changes made (for updates)"
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, help_text="Additional details"),
                ),
                (
                    "result",
                    models.CharField(
                        default="success",
                        help_text="Result of the action",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, help_text="HTTP method", max_length=10
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="Request path", max_length=1000
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                ],
            },
        ),
    ]
