# Generated by Django 5.2.13 on 2026-04-29 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="事件ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="事件时间",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True, db_index=True, null=True, verbose_name="租户ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("system", "系统事件"),
                            ("business", "业务事件"),
                            ("security", "安全事件"),
                            ("alert", "告警事件"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="事件名称"
                    ),
                ),
                ("message", models.TextField(verbose_name="事件消息")),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="事件详情"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "调试"),
                            ("info", "信息"),
                            ("notice", "通知"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("critical", "严重"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=20,
                        verbose_name="事件级别",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="事件产生的来源，如服务名、模块名",
                        max_length=100,
                        verbose_name="事件来源",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="资源类型"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=100, verbose_name="资源ID"),
                ),
                (
                    "user_email",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="用户邮箱"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="用户姓名"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, max_length=100, verbose_name="请求ID"),
                ),
                (
                    "is_handled",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理时间"
                    ),
                ),
                ("handle_note", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
            ],
            options={
                "verbose_name": "事件日志",
                "verbose_name_plural": "事件日志",
                "db_table": "event_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="error_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="错误代码"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="地理位置"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, verbose_name="元数据"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_id",
            field=models.CharField(
                blank=True,
                help_text="用于追踪请求链路",
                max_length=100,
                verbose_name="请求ID",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource_name",
            field=models.CharField(
                blank=True,
                help_text="资源显示名称，便于日志阅读",
                max_length=255,
                verbose_name="资源名称",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="会话ID"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="tenant_id",
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name="租户ID"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_email",
            field=models.CharField(
                blank=True,
                help_text="冗余存储，避免用户删除后无法追溯",
                max_length=255,
                verbose_name="用户邮箱",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user_name",
            field=models.CharField(
                blank=True,
                help_text="冗余存储，避免用户删除后无法追溯",
                max_length=255,
                verbose_name="用户姓名",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建"),
                    ("update", "更新"),
                    ("delete", "删除"),
                    ("access", "访问"),
                    ("execute", "执行"),
                    ("login", "登录"),
                    ("logout", "登出"),
                    ("export", "导出"),
                    ("import", "导入"),
                    ("enable", "启用"),
                    ("disable", "禁用"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="包含 before、after、changed_fields 等信息",
                verbose_name="变更详情",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.TextField(
                blank=True, help_text="人类可读的操作描述", verbose_name="操作描述"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="错误信息"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="日志ID",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP地址"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(blank=True, max_length=10, verbose_name="请求方法"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="请求路径"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="资源ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("user", "用户"),
                    ("tenant", "租户"),
                    ("license", "许可证"),
                    ("proxy", "代理"),
                    ("repository", "存储库"),
                    ("backup_task", "备份任务"),
                    ("recovery_task", "恢复任务"),
                    ("policy", "备份策略"),
                    ("source_resource", "备份源"),
                    ("gateway", "网关"),
                    ("session", "会话"),
                    ("system", "系统"),
                    ("audit_log", "审计日志"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="result",
            field=models.CharField(
                choices=[
                    ("success", "成功"),
                    ("failure", "失败"),
                    ("partial", "部分成功"),
                ],
                default="success",
                max_length=20,
                verbose_name="操作结果",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="操作时间",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=500, verbose_name="用户代理"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant_id", "-timestamp"], name="audit_logs_tenant__79c676_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["result"], name="audit_logs_result_df14e3_idx"),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["timestamp"], name="event_logs_timesta_24e1a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["tenant_id", "-timestamp"], name="event_logs_tenant__bdda86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["event_type"], name="event_logs_event_t_d63704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["event_name"], name="event_logs_event_n_8db346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["severity"], name="event_logs_severit_180529_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["is_handled"], name="event_logs_is_hand_5d81f1_idx"
            ),
        ),
    ]
