# Generated by Django 5.2.14 on 2026-05-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit_log",
            "0002_eventlog_alter_auditlog_options_auditlog_error_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="request_body",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="请求体数据（敏感字段已脱敏）",
                verbose_name="请求体",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_query",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="URL查询参数",
                verbose_name="查询参数",
            ),
        ),
    ]
