# Generated by Django 5.2.13 on 2026-04-22 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup_tasks', '0001_initial'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Recovery task name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Task description')),
                ('recovery_type', models.CharField(choices=[('original', 'Original Location'), ('new_location', 'New Location'), ('export', 'Export')], default='original', help_text='Type of recovery', max_length=20)),
                ('target_path', models.CharField(blank=True, help_text='Target path for new location recovery', max_length=4096)),
                ('file_patterns', models.JSONField(blank=True, default=list, help_text='File patterns to include in recovery')),
                ('exclude_patterns', models.JSONField(blank=True, default=list, help_text='File patterns to exclude')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current task status', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('restored_files', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('restored_size', models.BigIntegerField(default=0)),
                ('skipped_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(help_text='Source snapshot for recovery', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_tasks', to='backup_tasks.backupsnapshot')),
                ('target_node', models.ForeignKey(help_text='Target node for recovery', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_tasks', to='nodes.node')),
                ('user', models.ForeignKey(help_text='User who initiated the recovery', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='recovery_ta_status_7d3e1e_idx'), models.Index(fields=['target_node', 'status'], name='recovery_ta_target__8d16ac_idx'), models.Index(fields=['snapshot', 'status'], name='recovery_ta_snapsho_e31f35_idx')],
            },
        ),
    ]
