# Generated by Django 5.2.14 on 2026-05-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0015_proxy_retention_task_types'),
        ('recovery_tasks', '0002_add_tenant_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverytask',
            name='conflict_policy',
            field=models.CharField(choices=[('skip', 'Skip Existing Files'), ('overwrite', 'Overwrite Existing Files'), ('rename', 'Restore With New Name')], default='skip', help_text='How to handle files that already exist at the target', max_length=20),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='current_file',
            field=models.CharField(blank=True, help_text='Current file being restored', max_length=1024),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='eta',
            field=models.CharField(blank=True, help_text='Estimated time remaining', max_length=64),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Additional recovery options'),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text='Recovery execution priority', max_length=20),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='proxy_task',
            field=models.ForeignKey(blank=True, help_text='Latest proxy task dispatched for this recovery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_tasks', to='nodes.proxytask'),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='restore_scope',
            field=models.CharField(choices=[('entire_snapshot', 'Entire Snapshot'), ('selected_paths', 'Selected Files and Folders')], default='entire_snapshot', help_text='Whether to restore the whole snapshot or selected paths', max_length=24),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='selected_paths',
            field=models.JSONField(blank=True, default=list, help_text='Selected snapshot-relative paths for granular recovery'),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='speed_mbps',
            field=models.FloatField(default=0.0, help_text='Current restore speed in MB/s'),
        ),
        migrations.AddField(
            model_name='recoverytask',
            name='status_message',
            field=models.TextField(blank=True, help_text='Human readable execution status'),
        ),
    ]
