# Generated by Django 5.2.14 on 2026-05-19 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_tasks', '0008_snapshot_retention_state'),
        ('nodes', '0015_proxy_retention_task_types'),
        ('recovery_tasks', '0003_recoverytask_conflict_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('retry', 'Retry'), ('precheck', 'Precheck')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('current_file', models.CharField(blank=True, max_length=1024)),
                ('total_files', models.IntegerField(default=0)),
                ('restored_files', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('restored_size', models.BigIntegerField(default=0)),
                ('skipped_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('speed_mbps', models.FloatField(default=0.0)),
                ('eta', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proxy_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_runs', to='nodes.proxytask')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_runs', to='backup_tasks.backupsnapshot')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_runs', to='nodes.node')),
                ('task', models.ForeignKey(help_text='Recovery task this execution belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='recovery_tasks.recoverytask')),
            ],
            options={
                'db_table': 'recovery_task_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='recovery_ta_task_id_633ce1_idx'), models.Index(fields=['status'], name='recovery_ta_status_e45902_idx'), models.Index(fields=['proxy_task'], name='recovery_ta_proxy_t_7fc35d_idx')],
            },
        ),
    ]
