# Generated by Django 5.2.14 on 2026-05-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery_tasks', '0004_recoveryrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoveryrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='recoverytask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', help_text='Current task status', max_length=20),
        ),
    ]
