# Generated by Django 5.2.13 on 2026-04-27 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Repository name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Repository description"),
                ),
                (
                    "repo_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Filesystem"),
                            ("nfs", "NFS Share"),
                            ("s3", "Amazon S3"),
                            ("azure", "Azure Blob Storage"),
                            ("gcs", "Google Cloud Storage"),
                        ],
                        default="s3",
                        help_text="Repository type",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Connection configuration"
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text="Encrypted credentials for authentication",
                    ),
                ),
                (
                    "kopia_initialized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether Kopia repository has been initialized",
                    ),
                ),
                (
                    "kopia_repository_id",
                    models.CharField(
                        blank=True,
                        help_text="Kopia repository unique identifier",
                        max_length=255,
                    ),
                ),
                (
                    "encryption_algorithm",
                    models.CharField(
                        blank=True,
                        default="AES256-GCM-HMAC-SHA256",
                        help_text="Encryption algorithm used by Kopia",
                        max_length=50,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text="Storage path or bucket name (deprecated, use config)",
                        max_length=1024,
                    ),
                ),
                (
                    "capacity",
                    models.BigIntegerField(
                        default=0, help_text="Total capacity in bytes (0 = unlimited)"
                    ),
                ),
                (
                    "used_space",
                    models.BigIntegerField(default=0, help_text="Used space in bytes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initializing", "Initializing"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="inactive",
                        help_text="Repository status",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.TextField(
                        blank=True, help_text="Status message or error details"
                    ),
                ),
                (
                    "last_connection_test",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last connection test timestamp",
                        null=True,
                    ),
                ),
                (
                    "connection_test_result",
                    models.TextField(blank=True, help_text="Connection test result"),
                ),
                (
                    "supports_compression",
                    models.BooleanField(
                        default=True, help_text="Supports data compression"
                    ),
                ),
                (
                    "supports_encryption",
                    models.BooleanField(
                        default=True, help_text="Supports data encryption"
                    ),
                ),
                (
                    "compression_type",
                    models.CharField(
                        blank=True,
                        default="zstd",
                        help_text="Compression algorithm used",
                        max_length=50,
                    ),
                ),
                (
                    "is_readonly",
                    models.BooleanField(
                        default=False, help_text="Repository is read-only"
                    ),
                ),
                (
                    "snapshot_count",
                    models.IntegerField(
                        default=0, help_text="Number of snapshots in repository"
                    ),
                ),
                (
                    "last_backup_at",
                    models.DateTimeField(
                        blank=True, help_text="Last backup timestamp", null=True
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, help_text="Last synchronization time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bound_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Node that performs operations on this repository",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repositories",
                        to="nodes.node",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Repository owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "repositories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["repo_type"], name="repositorie_repo_ty_2952a1_idx"
                    ),
                    models.Index(
                        fields=["status"], name="repositorie_status_826bc4_idx"
                    ),
                    models.Index(
                        fields=["bound_node"], name="repositorie_bound_n_896b37_idx"
                    ),
                    models.Index(
                        fields=["kopia_initialized"],
                        name="repositorie_kopia_i_61c031_idx",
                    ),
                ],
            },
        ),
    ]
