# Generated by Django 5.2.13 on 2026-04-22 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Repository name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Repository description')),
                ('repo_type', models.CharField(choices=[('local', 'Local Filesystem'), ('nfs', 'NFS Share'), ('s3', 'Amazon S3'), ('azure', 'Azure Blob Storage'), ('gcs', 'Google Cloud Storage')], default='local', help_text='Repository type', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Repository configuration (credentials, paths, etc.)')),
                ('path', models.CharField(blank=True, help_text='Storage path or bucket name', max_length=1024)),
                ('capacity', models.BigIntegerField(default=0, help_text='Total capacity in bytes (0 = unlimited)')),
                ('used_space', models.BigIntegerField(default=0, help_text='Used space in bytes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', help_text='Repository status', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last synchronization time', null=True)),
                ('supports_compression', models.BooleanField(default=True, help_text='Supports data compression')),
                ('supports_encryption', models.BooleanField(default=False, help_text='Supports data encryption')),
                ('is_readonly', models.BooleanField(default=False, help_text='Repository is read-only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Repository owner', on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repositories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repo_type'], name='repositorie_repo_ty_2952a1_idx'), models.Index(fields=['status'], name='repositorie_status_826bc4_idx')],
            },
        ),
    ]
