# Generated by Django 5.2.13 on 2026-04-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="repo_type",
            field=models.CharField(
                choices=[
                    ("local", "Local Filesystem"),
                    ("nfs", "NFS Share"),
                    ("nas", "NAS/NFS/CIFS"),
                    ("s3", "Amazon S3"),
                    ("azure", "Azure Blob Storage"),
                    ("gcs", "Google Cloud Storage"),
                ],
                default="s3",
                help_text="Repository type",
                max_length=20,
            ),
        ),
    ]
