# Generated by Django 5.2.13 on 2026-04-25 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
        ("repository", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="bound_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Node that performs operations on this repository",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repositories",
                to="nodes.node",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="compression_type",
            field=models.CharField(
                blank=True,
                default="zstd",
                help_text="Compression algorithm used",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="connection_test_result",
            field=models.TextField(blank=True, help_text="Connection test result"),
        ),
        migrations.AddField(
            model_name="repository",
            name="credentials",
            field=models.JSONField(
                default=dict, help_text="Encrypted credentials for authentication"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="encryption_algorithm",
            field=models.CharField(
                blank=True,
                default="AES256-GCM-HMAC-SHA256",
                help_text="Encryption algorithm used by Kopia",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="kopia_initialized",
            field=models.BooleanField(
                default=False, help_text="Whether Kopia repository has been initialized"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="kopia_repository_id",
            field=models.CharField(
                blank=True,
                help_text="Kopia repository unique identifier",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_backup_at",
            field=models.DateTimeField(
                blank=True, help_text="Last backup timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_connection_test",
            field=models.DateTimeField(
                blank=True, help_text="Last connection test timestamp", null=True
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="snapshot_count",
            field=models.IntegerField(
                default=0, help_text="Number of snapshots in repository"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="status_message",
            field=models.TextField(
                blank=True, help_text="Status message or error details"
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="config",
            field=models.JSONField(default=dict, help_text="Connection configuration"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="name",
            field=models.CharField(
                help_text="Repository name", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="Storage path or bucket name (deprecated, use config)",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="repo_type",
            field=models.CharField(
                choices=[
                    ("local", "Local Filesystem"),
                    ("nfs", "NFS Share"),
                    ("s3", "Amazon S3"),
                    ("azure", "Azure Blob Storage"),
                    ("gcs", "Google Cloud Storage"),
                ],
                default="s3",
                help_text="Repository type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="status",
            field=models.CharField(
                choices=[
                    ("initializing", "Initializing"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                ],
                default="inactive",
                help_text="Repository status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="supports_encryption",
            field=models.BooleanField(
                default=True, help_text="Supports data encryption"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["bound_node"], name="repositorie_bound_n_896b37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["kopia_initialized"], name="repositorie_kopia_i_61c031_idx"
            ),
        ),
    ]
