# Generated by Django 5.2.14 on 2026-05-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_add_tenant_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='auto_cleanup_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic cleanup of old snapshots'),
        ),
        migrations.AddField(
            model_name='repository',
            name='cleanup_retention_days',
            field=models.IntegerField(default=90, help_text='Retention days for snapshots'),
        ),
        migrations.AddField(
            model_name='repository',
            name='cleanup_threshold_percent',
            field=models.IntegerField(default=90, help_text='Cleanup threshold percentage'),
        ),
        migrations.AddField(
            model_name='repository',
            name='health_check_results',
            field=models.JSONField(blank=True, default=dict, help_text='Last health check results'),
        ),
        migrations.AddField(
            model_name='repository',
            name='health_score',
            field=models.IntegerField(default=100, help_text='Health score (0-100)'),
        ),
        migrations.AddField(
            model_name='repository',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', help_text='Overall health status', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_cleanup_at',
            field=models.DateTimeField(blank=True, help_text='Last cleanup timestamp', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_health_check',
            field=models.DateTimeField(blank=True, help_text='Last health check timestamp', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='last_replication_at',
            field=models.DateTimeField(blank=True, help_text='Last successful replication timestamp', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='quota_bytes',
            field=models.BigIntegerField(blank=True, help_text='Quota limit in bytes (0 = unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='quota_enabled',
            field=models.BooleanField(default=False, help_text='Enable quota management'),
        ),
        migrations.AddField(
            model_name='repository',
            name='quota_warning_threshold',
            field=models.IntegerField(default=80, help_text='Warning threshold percentage (default: 80%)'),
        ),
        migrations.AddField(
            model_name='repository',
            name='replication_enabled',
            field=models.BooleanField(default=False, help_text='Enable replication to secondary storage'),
        ),
        migrations.AddField(
            model_name='repository',
            name='replication_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('pending', 'Pending'), ('syncing', 'Syncing'), ('error', 'Error'), ('uptodate', 'Up to date')], default='disabled', help_text='Replication status', max_length=20),
        ),
        migrations.AddField(
            model_name='repository',
            name='replication_target',
            field=models.ForeignKey(blank=True, help_text='Target repository for replication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replica_sources', to='repository.repository'),
        ),
    ]
