# Generated by Django 5.2.14 on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_repository_auto_cleanup_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='connection_test_details',
            field=models.JSONField(default=dict, blank=True, help_text='Detailed connection test results (connectivity, write_test, space_info)'),
        ),
    ]