# Generated by Django 5.2.14 on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_repository_connection_test_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='capacity',
            field=models.BigIntegerField(default=0, help_text='Actual total capacity in bytes detected from storage (0 = not detected)'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='quota_bytes',
            field=models.BigIntegerField(default=0, help_text='User-defined quota limit in bytes for capacity planning and alerts (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='quota_enabled',
            field=models.BooleanField(default=False, help_text='Enable quota management and alerts'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='quota_warning_threshold',
            field=models.IntegerField(default=80, help_text='Quota warning threshold percentage (alert when usage >= this % of quota, default: 80%)'),
        ),
    ]