# Generated by Django 5.2.13 on 2026-04-25 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Resource name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Resource description"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("nas", "NAS Storage"),
                            ("nfs", "NFS Share"),
                            ("cifs", "CIFS/SMB Share"),
                            ("s3", "Object Storage"),
                            ("local", "Local Filesystem"),
                        ],
                        default="nfs",
                        help_text="Resource type",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Connection configuration"
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict,
                        help_text="Encrypted credentials for authentication",
                    ),
                ),
                (
                    "mount_status",
                    models.CharField(
                        choices=[
                            ("unmounted", "Unmounted"),
                            ("mounted", "Mounted"),
                            ("error", "Mount Error"),
                        ],
                        default="unmounted",
                        help_text="Current mount status on bound node",
                        max_length=20,
                    ),
                ),
                (
                    "mount_point",
                    models.CharField(
                        blank=True,
                        help_text="Mount point path on the node, e.g., /mnt/hyperfilelens/source-001",
                        max_length=512,
                    ),
                ),
                (
                    "mount_error",
                    models.TextField(
                        blank=True, help_text="Mount error message if any"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="active",
                        help_text="Resource status",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.TextField(
                        blank=True, help_text="Status message or error details"
                    ),
                ),
                (
                    "last_connection_test",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last connection test timestamp",
                        null=True,
                    ),
                ),
                (
                    "connection_test_result",
                    models.TextField(blank=True, help_text="Connection test result"),
                ),
                (
                    "total_size",
                    models.BigIntegerField(
                        default=0, help_text="Total size of the source in bytes"
                    ),
                ),
                (
                    "file_count",
                    models.BigIntegerField(
                        default=0, help_text="Total number of files"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bound_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Node that mounts and accesses this resource",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_resources",
                        to="nodes.node",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Resource owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "source_resources",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type"], name="source_reso_resourc_bf7b92_idx"
                    ),
                    models.Index(
                        fields=["status"], name="source_reso_status_322d4c_idx"
                    ),
                    models.Index(
                        fields=["bound_node"], name="source_reso_bound_n_9239e0_idx"
                    ),
                ],
            },
        ),
    ]
