# Generated by Django 6.0.4 on 2026-04-28 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_resources', '0001_initial'),
        ('tenants', '0002_add_tenant_to_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceresource',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this resource belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_resources', to='tenants.tenant'),
        ),
    ]
