# Generated by Django 5.2.14 on 2026-05-19 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backup_tasks', '0009_backup_partial_status'),
        ('gateways', '0003_gateway_index_status_gateway_index_total_files_and_more'),
        ('tenants', '0006_alter_tenantinvitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotIndexJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_files', models.BigIntegerField(default=0)),
                ('indexed_files', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('indexed_bytes', models.BigIntegerField(default=0)),
                ('current_path', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_index_jobs', to='gateways.gateway')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_jobs', to='backup_tasks.backupsnapshot')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_index_jobs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_index_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotFileIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=64)),
                ('category', models.CharField(db_index=True, default='other', max_length=32)),
                ('size', models.BigIntegerField(default=0)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('is_directory', models.BooleanField(default=False)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_indexes', to='backup_tasks.backupsnapshot')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_indexes', to='insights.snapshotindexjob')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('related_paths', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('generated_by', models.CharField(default='rule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='backup_tasks.backupsnapshot')),
            ],
            options={
                'ordering': ['insight_type', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='snapshotindexjob',
            index=models.Index(fields=['snapshot', '-created_at'], name='insights_sn_snapsho_45113f_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotindexjob',
            index=models.Index(fields=['status'], name='insights_sn_status_64d1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotindexjob',
            index=models.Index(fields=['task_id'], name='insights_sn_task_id_cefb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotfileindex',
            index=models.Index(fields=['snapshot', 'category'], name='insights_sn_snapsho_193aae_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotfileindex',
            index=models.Index(fields=['snapshot', 'extension'], name='insights_sn_snapsho_5d1600_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotfileindex',
            index=models.Index(fields=['snapshot', '-size'], name='insights_sn_snapsho_5653b4_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotfileindex',
            index=models.Index(fields=['snapshot', 'content_hash'], name='insights_sn_snapsho_d297e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='snapshotfileindex',
            constraint=models.UniqueConstraint(fields=('snapshot', 'path'), name='uniq_snapshot_file_index_path'),
        ),
        migrations.AddIndex(
            model_name='snapshotinsight',
            index=models.Index(fields=['snapshot', 'insight_type'], name='insights_sn_snapsho_6efb06_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotinsight',
            index=models.Index(fields=['severity'], name='insights_sn_severit_3ad9fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='snapshotinsight',
            constraint=models.UniqueConstraint(fields=('snapshot', 'insight_type'), name='uniq_snapshot_insight_type'),
        ),
    ]
