# Generated by Django 5.2.14 on 2026-05-20 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_tasks', '0009_backup_partial_status'),
        ('gateways', '0003_gateway_index_status_gateway_index_total_files_and_more'),
        ('insights', '0001_initial'),
        ('tenants', '0006_alter_tenantinvitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotAIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(default='summarize', max_length=32)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('query', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(default='zh-CN', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_ai_jobs', to='gateways.gateway')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='backup_tasks.backupsnapshot')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_ai_jobs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['snapshot', '-created_at'], name='insights_sn_snapsho_878b17_idx'), models.Index(fields=['status'], name='insights_sn_status_6db5cf_idx'), models.Index(fields=['job_type'], name='insights_sn_job_typ_ce5380_idx'), models.Index(fields=['task_id'], name='insights_sn_task_id_5ff4d4_idx')],
            },
        ),
    ]
