# Generated by Django 5.2.13 on 2026-04-22 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Policy name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Policy description')),
                ('frequency', models.CharField(choices=[('manual', 'Manual'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='Backup frequency', max_length=20)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('differential', 'Differential Backup')], default='full', help_text='Type of backup to perform', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, help_text='Time of day to run backup', null=True)),
                ('schedule_day', models.IntegerField(blank=True, help_text='Day of week/month for backup', null=True)),
                ('retention_days', models.IntegerField(default=30, help_text='Number of days to retain backups')),
                ('retention_snapshots', models.IntegerField(default=10, help_text='Maximum number of snapshots to keep')),
                ('retention_before_backup', models.BooleanField(default=True, help_text='Keep snapshots before running new backup')),
                ('compression_enabled', models.BooleanField(default=True, help_text='Enable compression')),
                ('encryption_enabled', models.BooleanField(default=False, help_text='Enable encryption')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Policy owner', on_delete=django.db.models.deletion.CASCADE, related_name='backup_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
