# Generated by Django 6.0.4 on 2026-04-28 23:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique license identifier', primary_key=True, serialize=False)),
                ('license_key', models.CharField(help_text='Encrypted license key', max_length=64, unique=True)),
                ('licensee_name', models.CharField(help_text='Name of the licensed organization/individual', max_length=200)),
                ('licensee_email', models.EmailField(help_text='Contact email for the licensee', max_length=254)),
                ('licensee_company', models.CharField(blank=True, help_text='Company name (if applicable)', max_length=200, null=True)),
                ('product', models.CharField(default='HyperFileLens', help_text='Product name', max_length=50)),
                ('edition', models.CharField(choices=[('community', 'Community Edition'), ('pro', 'Professional Edition'), ('enterprise', 'Enterprise Edition')], default='community', help_text='Product edition', max_length=20)),
                ('version', models.CharField(default='1.0', help_text='Licensed version', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True, help_text='When the license was issued')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the license becomes valid')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the license expires (null = perpetual)', null=True)),
                ('max_tenants', models.PositiveIntegerField(default=1, help_text='Maximum number of tenants allowed')),
                ('max_users_per_tenant', models.PositiveIntegerField(default=10, help_text='Maximum users per tenant')),
                ('max_proxies_per_tenant', models.PositiveIntegerField(default=10, help_text='Maximum proxies per tenant')),
                ('max_repositories_per_tenant', models.PositiveIntegerField(default=5, help_text='Maximum repositories per tenant')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Maximum total storage in GB')),
                ('features', models.JSONField(default=dict, help_text='Feature flags and their enabled status')),
                ('modules', models.JSONField(default=list, help_text='List of enabled modules')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('trial', 'Trial')], default='active', help_text='Current license status', max_length=20)),
                ('signature', models.TextField(blank=True, help_text='Digital signature for verification', null=True)),
                ('fingerprint', models.CharField(blank=True, help_text='Machine fingerprint for binding', max_length=64, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this license', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'licenses_license',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_key'], name='licenses_li_license_46e8fe_idx'), models.Index(fields=['status'], name='licenses_li_status_40a808_idx'), models.Index(fields=['expires_at'], name='licenses_li_expires_2124f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'License Created'), ('activated', 'License Activated'), ('expired', 'License Expired'), ('revoked', 'License Revoked'), ('renewed', 'License Renewed'), ('verified', 'License Verified'), ('failed', 'Verification Failed')], help_text='Type of event', max_length=20)),
                ('message', models.TextField(help_text='Event description')),
                ('details', models.JSONField(default=dict, help_text='Additional event details')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(help_text='Related license', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='licenses.license')),
            ],
            options={
                'verbose_name': 'License Audit Log',
                'verbose_name_plural': 'License Audit Logs',
                'db_table': 'licenses_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
