# Generated by Django 6.0.4 on 2026-04-29 03:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_simplify_license_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique license identifier', primary_key=True, serialize=False)),
                ('license_key', models.CharField(help_text='License key from activation code', max_length=64, unique=True)),
                ('machine_code', models.CharField(help_text='Machine code: MAC + CPU + Tenant + User', max_length=64, unique=True)),
                ('max_tenants', models.PositiveIntegerField(default=1, help_text='Maximum number of tenants')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Maximum number of users (total across all tenants)')),
                ('max_proxies', models.PositiveIntegerField(default=5, help_text='Maximum number of proxies')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Maximum storage capacity in GB')),
                ('max_gateways', models.PositiveIntegerField(default=1, help_text='Maximum number of gateway nodes')),
                ('ai_insights_quota', models.PositiveIntegerField(default=100, help_text='Monthly AI insights quota (free tier)')),
                ('max_backup_tasks', models.PositiveIntegerField(default=10, help_text='Maximum concurrent backup tasks')),
                ('max_recovery_tasks', models.PositiveIntegerField(default=10, help_text='Maximum concurrent recovery tasks')),
                ('max_source_resources', models.PositiveIntegerField(default=20, help_text='Maximum number of source resources')),
                ('max_policies', models.PositiveIntegerField(default=50, help_text='Maximum number of backup policies')),
                ('max_repositories', models.PositiveIntegerField(default=5, help_text='Maximum number of backup repositories')),
                ('issued_at', models.DateTimeField(help_text='When the license was issued')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the license expires (null = perpetual)', null=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True, help_text='When the license was activated')),
                ('signature', models.TextField(help_text='Digital signature for verification')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', help_text='License status', max_length=20)),
                ('activated_by', models.ForeignKey(help_text='User who activated this license', on_delete=django.db.models.deletion.CASCADE, related_name='activated_licenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this license is bound to', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Generated machine code', max_length=64, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('cpu_id', models.CharField(blank=True, max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this code was used to activate', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_codes', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('generated', 'Machine Code Generated'), ('activated', 'License Activated'), ('expired', 'License Expired'), ('revoked', 'License Revoked'), ('limit_checked', 'Limit Checked'), ('limit_exceeded', 'Limit Exceeded')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='licenses.license')),
                ('machine_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='licenses.machinecode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.PositiveIntegerField(default=0)),
                ('proxies_count', models.PositiveIntegerField(default=0)),
                ('storage_used_gb', models.FloatField(default=0)),
                ('gateways_count', models.PositiveIntegerField(default=0)),
                ('backup_tasks_count', models.PositiveIntegerField(default=0)),
                ('recovery_tasks_count', models.PositiveIntegerField(default=0)),
                ('source_resources_count', models.PositiveIntegerField(default=0)),
                ('policies_count', models.PositiveIntegerField(default=0)),
                ('repositories_count', models.PositiveIntegerField(default=0)),
                ('ai_insights_used', models.PositiveIntegerField(default=0)),
                ('ai_insights_period', models.CharField(default='monthly', max_length=10)),
                ('ai_insights_reset_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Quota Usage',
                'verbose_name_plural': 'Quota Usages',
            },
        ),
    ]
