# Generated by Django 6.0.4 on 2026-04-29 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique license identifier', primary_key=True, serialize=False)),
                ('license_key', models.CharField(help_text='License key from activation code', max_length=64, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='License version (increments on each renewal/upgrade)')),
                ('change_type', models.CharField(choices=[('initial', 'Initial Activation'), ('renewal', 'Renewal (Extended Expiry)'), ('upgrade', 'Upgrade (Increased Limits)')], default='initial', help_text='Type of the latest change', max_length=20)),
                ('change_reason', models.CharField(blank=True, help_text='Reason for the latest change', max_length=200)),
                ('machine_code', models.CharField(help_text='Machine code: MAC + CPU + Tenant + User', max_length=64, unique=True)),
                ('max_tenants', models.PositiveIntegerField(default=1, help_text='Maximum number of tenants')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Maximum number of users')),
                ('max_proxies', models.PositiveIntegerField(default=5, help_text='Maximum number of proxies')),
                ('max_storage_gb', models.PositiveIntegerField(default=100, help_text='Maximum storage capacity in GB')),
                ('max_gateways', models.PositiveIntegerField(default=1, help_text='Maximum number of gateway nodes')),
                ('ai_insights_quota', models.PositiveIntegerField(default=100, help_text='Monthly AI insights quota')),
                ('max_backup_tasks', models.PositiveIntegerField(default=10, help_text='Maximum concurrent backup tasks')),
                ('max_recovery_tasks', models.PositiveIntegerField(default=10, help_text='Maximum concurrent recovery tasks')),
                ('max_source_resources', models.PositiveIntegerField(default=20, help_text='Maximum number of source resources')),
                ('max_policies', models.PositiveIntegerField(default=50, help_text='Maximum number of backup policies')),
                ('max_repositories', models.PositiveIntegerField(default=5, help_text='Maximum number of backup repositories')),
                ('issued_at', models.DateTimeField(help_text='When the license was issued')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the license expires (null = perpetual)', null=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True, help_text='When the license was activated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the license was last updated')),
                ('signature', models.TextField(help_text='Digital signature for verification')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', help_text='License status', max_length=20)),
                ('activated_by', models.ForeignKey(help_text='User who activated this license', on_delete=django.db.models.deletion.CASCADE, related_name='activated_licenses', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(help_text='Tenant this license is bound to (one-to-one)', on_delete=django.db.models.deletion.CASCADE, related_name='license', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('machine_code', models.CharField(max_length=64)),
                ('max_tenants', models.PositiveIntegerField()),
                ('max_users', models.PositiveIntegerField()),
                ('max_proxies', models.PositiveIntegerField()),
                ('max_storage_gb', models.PositiveIntegerField()),
                ('max_gateways', models.PositiveIntegerField()),
                ('ai_insights_quota', models.PositiveIntegerField()),
                ('max_backup_tasks', models.PositiveIntegerField()),
                ('max_recovery_tasks', models.PositiveIntegerField()),
                ('max_source_resources', models.PositiveIntegerField()),
                ('max_policies', models.PositiveIntegerField()),
                ('max_repositories', models.PositiveIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(help_text='When this license was archived')),
                ('status', models.CharField(max_length=20)),
                ('signature', models.TextField()),
                ('change_type', models.CharField(choices=[('initial', 'Initial Activation'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('revoked', 'Revoked')], max_length=20)),
                ('change_reason', models.CharField(blank=True, max_length=200)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_history', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_history', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'License History',
                'verbose_name_plural': 'License History',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Generated machine code', max_length=64, unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=20)),
                ('cpu_id', models.CharField(blank=True, max_length=100)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='machine_code_record', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_count', models.PositiveIntegerField(default=0)),
                ('proxies_count', models.PositiveIntegerField(default=0)),
                ('gateways_count', models.PositiveIntegerField(default=0)),
                ('backup_tasks_count', models.PositiveIntegerField(default=0)),
                ('recovery_tasks_count', models.PositiveIntegerField(default=0)),
                ('source_resources_count', models.PositiveIntegerField(default=0)),
                ('policies_count', models.PositiveIntegerField(default=0)),
                ('repositories_count', models.PositiveIntegerField(default=0)),
                ('storage_used_gb', models.FloatField(default=0.0)),
                ('ai_insights_used', models.PositiveIntegerField(default=0)),
                ('ai_reset_date', models.DateField(help_text='Date when AI quota was last reset')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='licenses.license')),
            ],
            options={
                'verbose_name': 'Quota Usage',
                'verbose_name_plural': 'Quota Usage',
            },
        ),
    ]
