# Generated by Django 6.0.4 on 2026-04-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotausage',
            name='ai_reset_date',
            field=models.DateField(blank=True, help_text='Date when AI quota was last reset', null=True),
        ),
    ]
