# Generated by Django 6.0.4 on 2026-04-29 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenants_count', models.PositiveIntegerField(default=0)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_proxies', models.PositiveIntegerField(default=0)),
                ('total_repositories', models.PositiveIntegerField(default=0)),
                ('storage_used_gb', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='When usage was last synced')),
            ],
            options={
                'verbose_name': 'Quota Usage',
                'verbose_name_plural': 'Quota Usage',
            },
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-issued_at'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='licenses_li_license_46e8fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='licenses_li_status_40a808_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='licenses_li_expires_2124f9_idx',
        ),
        migrations.RemoveField(
            model_name='licenseauditlog',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='licenseauditlog',
            name='message',
        ),
        migrations.AddField(
            model_name='license',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='SHA256 checksum of critical fields', max_length=64),
        ),
        migrations.AddField(
            model_name='license',
            name='machine_fingerprint',
            field=models.CharField(blank=True, help_text='Hardware fingerprint for machine binding', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='original_data',
            field=models.JSONField(blank=True, default=dict, help_text='Original imported license data (for verification)'),
        ),
        migrations.AddField(
            model_name='license',
            name='tamper_detected',
            field=models.BooleanField(default=False, help_text='Whether tampering was detected'),
        ),
        migrations.AddField(
            model_name='licenseauditlog',
            name='action',
            field=models.CharField(choices=[('imported', 'Imported'), ('activated', 'Activated'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('tamper_detected', 'Tamper Detected'), ('quota_exceeded', 'Quota Exceeded')], default='imported', help_text='Action type', max_length=30),
        ),
        migrations.AddField(
            model_name='licenseauditlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User agent', max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Feature flags'),
        ),
        migrations.AlterField(
            model_name='license',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the license was imported'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(help_text='License key (stored as hash)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='licensee_company',
            field=models.CharField(blank=True, help_text='Company name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='licensee_name',
            field=models.CharField(help_text='Name of the licensed organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_proxies_per_tenant',
            field=models.PositiveIntegerField(default=5, help_text='Maximum proxies per tenant'),
        ),
        migrations.AlterField(
            model_name='license',
            name='max_storage_gb',
            field=models.PositiveIntegerField(default=100, help_text='Maximum storage in GB'),
        ),
        migrations.AlterField(
            model_name='license',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Digital signature (RSA)'),
        ),
        migrations.AlterField(
            model_name='license',
            name='starts_at',
            field=models.DateTimeField(help_text='When the license becomes valid'),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('trial', 'Trial'), ('invalid', 'Invalid')], default='active', help_text='License status', max_length=20),
        ),
        migrations.AlterField(
            model_name='licenseauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the action occurred'),
        ),
        migrations.AlterField(
            model_name='licenseauditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, help_text='Additional details'),
        ),
        migrations.AlterField(
            model_name='licenseauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the action', null=True),
        ),
        migrations.AlterModelTable(
            name='license',
            table=None,
        ),
        migrations.AlterModelTable(
            name='licenseauditlog',
            table=None,
        ),
        migrations.AddField(
            model_name='quotausage',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usage', to='licenses.license'),
        ),
        migrations.RemoveField(
            model_name='license',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='license',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='license',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='license',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='license',
            name='updated_at',
        ),
    ]
