# Generated by Django 6.0.4 on 2026-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_security_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When the license was activated (bound to machine)', null=True),
        ),
    ]
