# Generated by Django 5.2.13 on 2026-04-27 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Feature name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Feature description"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether feature is enabled"
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Feature configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_features",
            },
        ),
        migrations.CreateModel(
            name="AIQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.TextField(help_text="User's query text")),
                (
                    "query_type",
                    models.CharField(
                        choices=[
                            ("search", "Search"),
                            ("analysis", "Analysis"),
                            ("summary", "Summary"),
                            ("comparison", "Comparison"),
                        ],
                        default="search",
                        help_text="Type of query",
                        max_length=20,
                    ),
                ),
                (
                    "target_paths",
                    models.JSONField(
                        blank=True, default=list, help_text="Paths to search/analyze"
                    ),
                ),
                (
                    "file_types",
                    models.JSONField(
                        blank=True, default=list, help_text="File types to focus on"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Query status",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, help_text="Query results"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, help_text="AI model used for query", max_length=100
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, help_text="Number of tokens used"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When query completed", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the query",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
