# Generated by Django 6.0.4 on 2026-04-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_query', '0001_initial'),
        ('tenants', '0005_add_tenant_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquery',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant who owns this query', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_queries', to='tenants.tenant'),
        ),
    ]
