# Generated by Django 5.2.14 on 2026-05-20 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_query', '0002_add_tenant_field'),
        ('tenants', '0006_alter_tenantinvitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(choices=[('openai_compatible', 'OpenAI Compatible'), ('openai', 'OpenAI'), ('local', 'Local Fallback')], default='openai_compatible', max_length=32)),
                ('base_url', models.URLField(blank=True, default='https://api.openai.com/v1')),
                ('api_key', models.TextField(blank=True)),
                ('default_model', models.CharField(blank=True, default='gpt-4.1-mini', max_length=128)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_providers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ai_providers',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='ai_provider_tenant__bee160_idx'), models.Index(fields=['tenant', 'is_default'], name='ai_provider_tenant__9895d2_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_tenant_ai_provider_name')],
            },
        ),
    ]
